### ISSUE TITLE
download_yd_data.py fails as API returns status code >400

### ISSUE THREAD

**Issue by fazliimam** [youdescribe-sfsu/You-Described-We-Archived#2]
I get the following error for download_yd_data.py", line 238, in main:
`print(response.json()['message'])`
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This happened due to the api returning status code > 400. But I answered all the questions appropriately.

**Comment by ManaliSeth** [comment]
The API issues are now resolved. Please try to run the script again and it should work as expected.
