### ISSUE TITLE
Error 522 when attempting to run the download script

### ISSUE THREAD

**Issue by alimuldal** [youdescribe-sfsu/You-Described-We-Archived#3]
Requests to https://ai.youdescribe.org/api are consistently returning error 522 (Connection timed out), so I'm currently unable to register for an API key to download the dataset. I suspect the server is unhealthy.

**Comment by ManaliSeth** [comment]
Please attempt to rerun the script. Hopefully, you shouldn't encounter any more errors with this URL. Feel free to inform me if you face any challenges while downloading audio clips.
